- name: Update NetasCode YAML from CSV
  hosts: localhost
  gather_facts: no
  vars:
    raw_items: "{{ lookup('csvfile', 'csv/interfaces.csv', delimiter=',', columns=['switch','interface','description','policy_group']) }}"
  tasks:
    - name: Convert list of dicts
      set_fact:
        raw_interfaces: "{{ raw_items | map('community.general.dict_kv') | list }}"

    - name: Filter for action == 'update'
      set_fact:
        interfaces: "{{ raw_interfaces | selectattr('action', 'equalto', 'update') | list }}"

    - name: Fail if attempting to update without explicit marker
      fail:
        msg: "Blocked unsafe update operation. Confirm records in csv/interfaces.csv are intended."
      when: interfaces | length > 2


    - name: Prompt for confirmation
      pause:
        prompt: "You are about to UPDATE {% for item in interfaces %}\n  - { item }{% endfor %}\nType 'yes' to continue:"
        echo: yes
      register: user_input

    - name: Abort if user did not confirm
      fail:
        msg: "Operation cancelled by user."
      when: user_input.user_input != 'yes'
    - name: Render YAML for Update
      template:
        src: templates/interfaces.j2
        dest: nac-configs/interfaces.yml
