- name: Update NetasCode YAML from CSV
  hosts: localhost
  gather_facts: no
  vars:
    raw_items: "{{ lookup('csvfile', 'csv/vpcs.csv', delimiter=',', columns=['id','description','switch1','interface1','switch2','interface2']) }}"
  tasks:
    - name: Convert list of dicts
      set_fact:
        raw_vpcs: "{{ raw_items | map('community.general.dict_kv') | list }}"

    - name: Filter for action == 'update'
      set_fact:
        vpcs: "{{ raw_vpcs | selectattr('action', 'equalto', 'update') | list }}"

    - name: Fail if attempting to update without explicit marker
      fail:
        msg: "Blocked unsafe update operation. Confirm records in csv/vpcs.csv are intended."
      when: vpcs | length > 2


    - name: Prompt for confirmation
      pause:
        prompt: "You are about to UPDATE {% for item in vpcs %}\n  - { item }{% endfor %}\nType 'yes' to continue:"
        echo: yes
      register: user_input

    - name: Abort if user did not confirm
      fail:
        msg: "Operation cancelled by user."
      when: user_input.user_input != 'yes'
    - name: Render YAML for Update
      template:
        src: templates/vpcs.j2
        dest: nac-configs/vpcs.yml
