- name: Create NetasCode YAML from CSV
  hosts: localhost
  gather_facts: no
  vars:
    raw_items: "{{ lookup('csvfile', 'csv/vrfs.csv', delimiter=',', columns=['name','tenant','type']) }}"
  tasks:
    - name: Convert list of dicts
      set_fact:
        raw_vrfs: "{{ raw_items | map('community.general.dict_kv') | list }}"

    - name: Filter for action == 'add'
      set_fact:
        vrfs: "{{ raw_vrfs | selectattr('action', 'equalto', 'add') | list }}"

    - name: Fail if attempting to add without explicit marker
      fail:
        msg: "Blocked unsafe add operation. Confirm records in csv/vrfs.csv are intended."
      when: vrfs | length > 2

    - name: Render YAML for Create
      template:
        src: templates/vrfs.j2
        dest: nac-configs/vrfs.yml
