- name: Remove NetasCode YAML from CSV
  hosts: localhost
  gather_facts: no
  vars:
    raw_items: "{{ lookup('csvfile', 'csv/vlans.csv', delimiter=',', columns=['id','name','vrf','svi_ip']) }}"
  tasks:
    - name: Convert list of dicts
      set_fact:
        raw_vlans: "{{ raw_items | map('community.general.dict_kv') | list }}"

    - name: Filter for action == 'remove'
      set_fact:
        vlans: "{{ raw_vlans | selectattr('action', 'equalto', 'remove') | list }}"

    - name: Fail if attempting to remove without explicit marker
      fail:
        msg: "Blocked unsafe remove operation. Confirm records in csv/vlans.csv are intended."
      when: vlans | length > 2


    - name: Prompt for confirmation
      pause:
        prompt: "You are about to REMOVE {% for item in vlans %}\n  - { item }{% endfor %}\nType 'yes' to continue:"
        echo: yes
      register: user_input

    - name: Abort if user did not confirm
      fail:
        msg: "Operation cancelled by user."
      when: user_input.user_input != 'yes'
    - name: Render YAML for Remove
      template:
        src: templates/vlans.j2
        dest: nac-configs/vlans.yml
